# Generated by Django 5.1.1 on 2024-10-04 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_query'),
    ]

    operations = [
        migrations.RenameField(
            model_name='query',
            old_name='stu_contact',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='query',
            old_name='stu_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='query',
            old_name='stu_name',
            new_name='name',
        ),
    ]
