# Generated by Django 5.1.1 on 2024-10-04 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_stu_contact_query_contact_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='query',
            old_name='contact',
            new_name='stu_contact',
        ),
        migrations.RenameField(
            model_name='query',
            old_name='email',
            new_name='stu_email',
        ),
        migrations.RenameField(
            model_name='query',
            old_name='name',
            new_name='stu_name',
        ),
        migrations.RenameField(
            model_name='query',
            old_name='query',
            new_name='stu_query',
        ),
    ]
