# Generated by Django 5.1.1 on 2024-10-22 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_delete_aadhar_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aadhar',
            fields=[
                ('aadhar', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.IntegerField()),
                ('aadhar_no', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.aadhar')),
            ],
        ),
    ]
