# Generated by Django 5.1.2 on 2024-10-25 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_skill_profile_city_remove_profile_exp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='quali',
        ),
    ]
