# Generated by Django 5.1.2 on 2024-10-25 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_profile_quali'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Aadhar',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
