# Generated by Django 5.1.2 on 2024-10-24 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='aadhar_no',
        ),
        migrations.RemoveField(
            model_name='user',
            name='department_name',
        ),
    ]
